# Generated by Django 6.0.6 on 2026-07-13 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DATA_scope', '0004_employee_estado_custom_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('break_minutes', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('late', 'Atraso'), ('leave', 'Permiso/Licencia'), ('holiday', 'Feriado'), ('remote', 'Remoto')], default='present', max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Importacion'), ('device', 'Reloj control')], default='manual', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='DATA_scope.employee')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'db_table': 'attendance_record',
                'ordering': ['-date', 'employee__nombre'],
                'permissions': [('access_attendance_module', 'Puede acceder al modulo de asistencia'), ('manage_attendance_records', 'Puede administrar registros de asistencia'), ('view_attendance_reports', 'Puede ver reportes de asistencia'), ('export_attendance_reports', 'Puede exportar reportes de asistencia')],
                'indexes': [models.Index(fields=['date'], name='attendance__date_21321a_idx'), models.Index(fields=['employee', 'date'], name='attendance__employe_9ec8ab_idx'), models.Index(fields=['status'], name='attendance__status_40d6e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='attendance_unique_employee_date')],
            },
        ),
    ]
