# Generated by Django 6.0.6 on 2026-07-13 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(choices=[('unidad', 'Unidad'), ('caja', 'Caja'), ('kg', 'Kg'), ('litro', 'Litro'), ('servicio', 'Servicio')], default='unidad', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'inventory_product',
                'ordering': ['sku'],
                'permissions': [('access_inventory_module', 'Puede acceder al modulo de inventario'), ('manage_inventory_config', 'Puede administrar productos y bodegas'), ('manage_inventory_stock', 'Puede registrar movimientos de inventario'), ('view_inventory_reports', 'Puede ver reportes de inventario')],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'inventory_warehouse',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('adjustment', 'Ajuste')], max_length=16)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('applied', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='Inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='Inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'db_table': 'inventory_stock_movement',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='inventory_s_date_98dec9_idx'), models.Index(fields=['movement_type'], name='inventory_s_movemen_447eca_idx'), models.Index(fields=['product', 'warehouse'], name='inventory_s_product_2104c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='Inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='Inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Saldo de stock',
                'verbose_name_plural': 'Saldos de stock',
                'db_table': 'inventory_stock_balance',
                'ordering': ['product__sku', 'warehouse__code'],
                'indexes': [models.Index(fields=['product', 'warehouse'], name='inventory_s_product_434844_idx'), models.Index(fields=['warehouse'], name='inventory_s_warehou_32c503_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse'), name='inventory_unique_product_warehouse')],
            },
        ),
    ]
