# Generated by Django 6.0.6 on 2026-07-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_ficha', models.CharField(max_length=32, unique=True)),
                ('rut', models.CharField(blank=True, max_length=32)),
                ('nombre', models.CharField(max_length=255)),
                ('division', models.CharField(blank=True, max_length=120)),
                ('afp', models.CharField(blank=True, max_length=80)),
                ('isapre', models.CharField(blank=True, max_length=80)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_retiro', models.DateTimeField(blank=True, null=True)),
                ('horario_trabajo', models.CharField(blank=True, max_length=120)),
                ('jornada_vs', models.CharField(blank=True, max_length=8)),
                ('jornada_contrato', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'db_table': 'data_employee',
                'ordering': ['nombre', 'codigo_ficha'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('categoria', models.CharField(choices=[('asignaciones_familiares', 'Asignaciones familiares'), ('contribucion_empleador', 'Contribucion empleador'), ('descuentos_legales_previsionales', 'Descuentos legales previsionales'), ('haberes_exentos_no_imponibles', 'Haberes exentos no imponibles'), ('haberes_normales_imponibles', 'Haberes normales imponibles'), ('otros_descuentos', 'Otros descuentos'), ('provisiones', 'Provisiones'), ('totales', 'Totales')], max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('requiere_confirmacion', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'data_payroll_item',
                'ordering': ['categoria', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(max_length=6, unique=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'data_payroll_period',
                'ordering': ['periodo'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=16)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='DATA_scope.employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='DATA_scope.payrollitem')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='DATA_scope.payrollperiod')),
            ],
            options={
                'db_table': 'data_payroll_entry',
                'ordering': ['period__periodo', 'employee__codigo_ficha', 'item__categoria', 'item__codigo'],
                'indexes': [models.Index(fields=['period', 'employee'], name='data_payrol_period__4ea5b7_idx'), models.Index(fields=['item'], name='data_payrol_item_id_a01eeb_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'period', 'item'), name='unique_payroll_entry_employee_period_item')],
            },
        ),
        migrations.CreateModel(
            name='PayrollSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(max_length=80, unique=True)),
                ('rut_empresa', models.CharField(blank=True, max_length=32)),
                ('sueldo_base', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('dias_laborales', models.PositiveSmallIntegerField(default=0)),
                ('dias_trabajados', models.PositiveSmallIntegerField(default=0)),
                ('dias_licencias', models.PositiveSmallIntegerField(default=0)),
                ('dias_permisos', models.PositiveSmallIntegerField(default=0)),
                ('dias_ausencias', models.PositiveSmallIntegerField(default=0)),
                ('dias_suspendidos', models.PositiveSmallIntegerField(default=0)),
                ('horas_no_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_empresa', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('total_haberes_imponibles', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('total_haberes_no_imponibles', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('total_haberes_no_imponibles_tributables', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('total_descuentos_legales', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('total_otros_descuentos', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('sueldo_liquido', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('base_tributable', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('impuesto', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('pago_prevision', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('pago_salud_obligatoria', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('pago_salud_voluntaria', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('pago_prevision_voluntaria', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('seguro_cesantia_trabajador', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('seguro_cesantia_empleador', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('mutual_empleador', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('pago_sis_empleador', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('afp_prevision_empleador', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('ley_sanna', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('otros_aportes_patronales', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('saldo_sobregiro', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_summaries', to='DATA_scope.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_summaries', to='DATA_scope.payrollperiod')),
            ],
            options={
                'db_table': 'data_payroll_summary',
                'ordering': ['period__periodo', 'employee__codigo_ficha'],
                'indexes': [models.Index(fields=['period', 'employee'], name='data_payrol_period__80c00f_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'period'), name='unique_payroll_summary_employee_period')],
            },
        ),
    ]
