# Generated by Django 6.0.6 on 2026-07-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DATA_scope', '0002_importrun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['nombre', 'codigo_ficha'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.AlterModelOptions(
            name='importrun',
            options={'ordering': ['-created_at'], 'verbose_name': 'Carga ETL', 'verbose_name_plural': 'Cargas ETL'},
        ),
        migrations.AlterModelOptions(
            name='payrollentry',
            options={'ordering': ['period__periodo', 'employee__codigo_ficha', 'item__categoria', 'item__codigo'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='payrollitem',
            options={'ordering': ['categoria', 'codigo'], 'verbose_name': 'Item de remuneracion', 'verbose_name_plural': 'Items de remuneracion'},
        ),
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={'ordering': ['periodo'], 'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
        migrations.AlterModelOptions(
            name='payrollsummary',
            options={'ordering': ['period__periodo', 'employee__codigo_ficha'], 'verbose_name': 'Liquidacion', 'verbose_name_plural': 'Liquidaciones'},
        ),
    ]
